alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: "email-notifier"
    receivers:
      - name: "email-notifier"
        email_configs:
          - to: "hkamguin@gmail.com"
            from: "efreidevops2025@gmail.com"
            smarthost: "smtp.gmail.com:587"
            auth_username: "efreidevops2025@gmail.com"
            auth_password: "cnhp oqkx yytp engx"
            send_resolved: true
  extraArgs:
    log.level: debug

additionalPrometheusRules:
  - name: podnotrunning
    groups:
      - name: kubernetes-alerts
        rules:
          - alert: PodNotRunning
            expr: kube_pod_status_phase{phase!="Running"} > 0
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "Pod {{ $labels.pod }} is not running"
              description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has not been running for 1 minutes."