apiVersion: apps/v1
kind: Deployment
metadata:
  name: efreiapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efreiapp
  template:
    metadata:
      labels:
        app: efreiapp
    spec:
      containers:
      - name: efreiapp
        image: efreiapp:latest 
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
