apiVersion: v1
kind: Pod
metadata:
  name: memory-load
  namespace: default
spec:
  containers:
    - name: memory-stress
      image: polinux/stress
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "600M", "--vm-hang", "1"]
