serverFiles:
  alerting_rules.yml:
    groups:
      - name: kubernetes-rules
        rules:
          - alert: PodNotRunning
            expr: kube_pod_status_phase{phase!="Running"} > 0
            for: 1m
            labels:
              severity: critical
            annotations:
              description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is not running."
              summary: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has not been running for more than 5 minutes."