name: Build and Deploy Locally

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: Set Docker permissions
        run: |
          sudo chmod 666 /var/run/docker.sock
          
      # Vérifier le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t efreiapp:latest ./webapi

      # Exécuter le conteneur Docker
      - name: Run Docker container
        run: |
          docker run -d -p 8079:8080 --name efreiapp-container efreiapp:latest
