name: Build and Deploy Locally

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t efreiapp:latest ./webapi

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name efreiapp-container efreiapp:latest
